import { useState, useMemo, createContext, useContext } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import gpuCsv from '../data/gpus.csv?raw'

// ─── Term explanation system ──────────────────────────────────────────────────

const TermCtx = createContext({ setTerm: () => {} })

const EXPLANATIONS = {
  ttft:            { term: 'TTFT',              body: 'Time To First Token — how long before the model starts streaming output. Directly affects perceived responsiveness in real-time apps.' },
  e2e_latency:     { term: 'E2E Latency',       body: 'End-to-End Latency — total time from user input to complete response, including all pipeline stages (ASR → model → TTS).' },
  throughput:      { term: 'Throughput',        body: 'Tokens per second (or images/min) generated by the whole cluster. Higher throughput means more users can be served at once.' },
  concurrent:      { term: 'Concurrent Users',  body: 'How many simultaneous sessions the cluster can hold in memory at once, limited by available KV cache space.' },
  kv_cache:        { term: 'KV Cache',          body: 'Key-Value Cache — memory reserved per active session for the transformer attention mechanism. Each open session needs a fixed slice of VRAM.' },
  nvlink:          { term: 'NVLink',            body: "NVIDIA's high-speed GPU interconnect. Cards share a unified memory pool and split a single model across them (tensor parallelism)." },
  pcie:            { term: 'PCIe',              body: 'PCI Express — standard expansion slot. No memory sharing between cards; each GPU must hold a full independent model copy.' },
  tensor_parallel: { term: 'Tensor Parallel',   body: 'A model is split across multiple GPUs. All cards cooperate on every inference, pooling their VRAM and compute.' },
  multi_instance:  { term: 'Multi-Instance',    body: 'Each GPU runs a fully independent copy of the model. More aggregate throughput, but no memory pooling between cards.' },
  fp16:            { term: 'FP16 / BF16',       body: '16-bit floating point — standard precision for LLM inference. Good balance of speed, memory use, and numerical accuracy.' },
  fp8:             { term: 'FP8',               body: '8-bit floating point — halves memory vs FP16 and roughly doubles throughput on Blackwell/Hopper. Small accuracy trade-off.' },
  tflops:          { term: 'TFLOPS',            body: 'Tera Floating Point Operations Per Second — raw compute throughput of the GPU. Higher = faster matrix multiplication.' },
  memory_bw:       { term: 'Memory Bandwidth',  body: 'How fast the GPU can stream weights from VRAM during inference. Token generation is bandwidth-bound, not compute-bound.' },
  tdp:             { term: 'TDP',               body: 'Thermal Design Power — peak sustained power draw in watts. Determines cooling requirements and electricity cost.' },
  hbm:             { term: 'HBM',               body: 'High Bandwidth Memory — stacked DRAM soldered onto the GPU package. Much faster than GDDR but more expensive. Used in data-center GPUs.' },
  gddr:            { term: 'GDDR6 / GDDR7',     body: 'Standard graphics memory. Lower bandwidth than HBM but cheaper. Used in workstation-class GPUs like the RTX 6000 Ada.' },
  generation:      { term: 'Generation',        body: 'Auto-regressive decoding — producing output tokens one at a time after the first token. Duration scales with response length.' },
  asr:             { term: 'ASR',               body: 'Automatic Speech Recognition — converts spoken audio to text (e.g. Whisper, Parakeet). First stage of a voice pipeline.' },
  tts:             { term: 'TTS',               body: 'Text-to-Speech — converts the model\'s text output to audio for the user (e.g. Kokoro). Last stage of a voice pipeline.' },
  gpu_memory:      { term: 'GPU Memory',        body: 'Total VRAM across all cards. Must fit the model weights plus KV cache for all active sessions simultaneously.' },
  power_draw:      { term: 'Power Draw',        body: 'Total electrical consumption at full load. At $0.10/kWh, 1 kW costs ~$876/year. Data centers add cooling overhead on top.' },
  architecture:    { term: 'Architecture',      body: 'The GPU microarchitecture generation. Blackwell (2025) > Hopper (2022) > Ada Lovelace (2022) in raw performance per watt.' },
  cluster_cost:    { term: 'Cluster Cost',      body: 'Estimated total hardware spend for this GPU configuration. Based on approximate market prices — actual quotes will vary.' },
  annual_power:    { term: 'Annual Power Cost', body: 'Electricity cost at full load for one year, assuming $0.10/kWh. Data centers typically add 1.4–1.6× for cooling (PUE).' },
  cost_per_user:   { term: 'Cost / User',       body: 'Cluster hardware cost divided by concurrent user capacity. Lower = more efficient use of capital.' },
  monthly_power:   { term: 'Monthly Power',     body: 'Estimated electricity cost per month at full utilisation, at $0.10/kWh.' },
}

function Term({ id, children }) {
  const { setTerm } = useContext(TermCtx)
  return (
    <span
      className="border-b border-dotted border-gray-400 cursor-help"
      onMouseEnter={() => setTerm(id)}
      onMouseLeave={() => setTerm(null)}
    >
      {children}
    </span>
  )
}

function ExplanationPanel({ termId }) {
  const entry = EXPLANATIONS[termId]
  return (
    <AnimatePresence>
      {entry && (
        <motion.div
          key={termId}
          initial={{ opacity: 0, x: 16 }}
          animate={{ opacity: 1, x: 0 }}
          exit={{ opacity: 0, x: 16 }}
          transition={{ duration: 0.2 }}
          className="fixed right-6 top-44 z-30 w-64
                     bg-white rounded-2xl shadow-xl border border-gray-100 p-5 pointer-events-none"
        >
          <p className="text-xs font-bold uppercase tracking-widest text-gray-400 mb-1 font-[Montserrat,sans-serif]">Term</p>
          <h4 className="text-lg font-bold text-gray-900 mb-2" style={{ fontFamily: 'Playfair Display, serif' }}>{entry.term}</h4>
          <p className="text-sm text-gray-600 leading-relaxed font-[Montserrat,sans-serif]">{entry.body}</p>
        </motion.div>
      )}
    </AnimatePresence>
  )
}

const KWH_RATE = 0.10  // $/kWh

function computeCosts(gpu, numCards, concurrentUsers) {
  const clusterCost    = gpu.priceUSD * numCards
  const annualPowerUSD = gpu.tdpW * numCards / 1000 * 8760 * KWH_RATE
  const monthlyPowerUSD = annualPowerUSD / 12
  const costPerUser    = concurrentUsers > 0 ? clusterCost / concurrentUsers : 0
  return { clusterCost, annualPowerUSD, monthlyPowerUSD, costPerUser }
}

function fmt$(n) {
  if (n >= 1_000_000) return `$${(n / 1_000_000).toFixed(2)}M`
  if (n >= 1_000)     return `$${Math.round(n / 1000)}K`
  return `$${Math.round(n)}`
}

function CostPanel({ gpu, numCards, concurrentUsers }) {
  const { clusterCost, annualPowerUSD, monthlyPowerUSD, costPerUser } = computeCosts(gpu, numCards, concurrentUsers)
  const rows = [
    { label: <Term id="cluster_cost">Cluster Cost</Term>,   value: fmt$(clusterCost),      sub: `${fmt$(gpu.priceUSD)} × ${numCards} cards` },
    { label: <Term id="cost_per_user">Cost / User</Term>,   value: fmt$(costPerUser),      sub: 'hardware amortised' },
    { label: <Term id="annual_power">Annual Power</Term>,   value: fmt$(annualPowerUSD),   sub: 'at $0.10 / kWh' },
    { label: <Term id="monthly_power">Monthly Power</Term>, value: fmt$(monthlyPowerUSD),  sub: 'full-load estimate' },
  ]
  return (
    <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5">
      <h3 className="text-xs font-bold uppercase tracking-widest text-gray-400 mb-4 font-[Montserrat,sans-serif]">
        Cost of Infrastructure
      </h3>
      <div className="grid grid-cols-2 gap-3">
        {rows.map(({ label, value, sub }, i) => (
          <div key={i} className="flex flex-col gap-0.5 min-w-0">
            <span className="text-xs font-medium text-gray-400 uppercase tracking-wider font-[Montserrat,sans-serif] leading-tight">{label}</span>
            <span className="text-2xl font-bold text-[#0071e3] leading-tight" style={{ fontFamily: 'Playfair Display, serif' }}>{value}</span>
            <span className="text-xs text-gray-400 font-[Montserrat,sans-serif]">{sub}</span>
          </div>
        ))}
      </div>
      <p className="text-[10px] text-gray-300 mt-4 font-[Montserrat,sans-serif] italic leading-snug">
        Prices are market estimates. Power assumes full utilisation.
      </p>
    </div>
  )
}

// ─── Workload Catalog ─────────────────────────────────────────────────────────
const WORKLOAD_CATALOG = {
  'voice-agent': {
    id: 'voice-agent',
    name: 'Real-time Voice Agent',
    tagline: 'How many simultaneous voice calls can this cluster support?',
    description: 'End-to-end voice AI — ASR speech recognition → LLM response → TTS synthesis',
    modelSizeGb: 14, modelLabel: '7B BF16 LLM',
    kvPerSessionGb: 0.5,
    avgResponseTokens: 50,
    pipelinePreMs: 100, pipelinePreLabel: 'ASR',
    pipelinePostMs: 80, pipelinePostLabel: 'TTS',
    sessionNoun: 'calls',
    throughputLabel: 'tokens/s',
    latencyLabel: 'E2E Latency',
    showTtft: true,
  },
  'llm-chat': {
    id: 'llm-chat',
    name: 'LLM Chat / API',
    tagline: 'How many concurrent chat users can this cluster serve?',
    description: 'Conversational AI serving — chat apps, REST completions API, streaming responses',
    modelSizeGb: 14, modelLabel: '7B BF16 LLM',
    kvPerSessionGb: 2,
    avgResponseTokens: 200,
    pipelinePreMs: 0, pipelinePreLabel: null,
    pipelinePostMs: 0, pipelinePostLabel: null,
    sessionNoun: 'users',
    throughputLabel: 'tokens/s',
    latencyLabel: 'Response Time',
    showTtft: true,
  },
}

// ─── GPU Catalog ──────────────────────────────────────────────────────────────
// ─── CSV parser ───────────────────────────────────────────────────────────────

function parseCSV(raw) {
  const lines = raw.trim().split('\n')
  const headers = lines[0].split(',').map(h => h.trim())
  return lines.slice(1).map(line => {
    const values = []
    let cur = '', inQ = false
    for (const ch of line) {
      if (ch === '"') { inQ = !inQ }
      else if (ch === ',' && !inQ) { values.push(cur.trim()); cur = '' }
      else { cur += ch }
    }
    values.push(cur.trim())
    return Object.fromEntries(headers.map((h, i) => [h, values[i] ?? '']))
  })
}

const _gpuRows = parseCSV(gpuCsv)

const GPU_CATALOG = Object.fromEntries(_gpuRows.map(r => [r.id, {
  id:             r.id,
  name:           r.name,
  shortName:      r.shortName,
  architecture:   r.architecture,
  memoryGb:       +r.memoryGb,
  memoryType:     r.memoryType,
  bandwidthTBs:   +r.bandwidthTBs,
  tdpW:           +r.tdpW,
  interconnect:   r.interconnect,
  nvlinkBw:       r.nvlinkBw || null,
  validCounts:    [1, 2, 3, 4, 5, 6, 7, 8],
  fp16Tflops:     +r.fp16Tflops,
  fp8Tflops:      +r.fp8Tflops,
  baseTpsPerCard: +r.baseTpsPerCard,
  baseTtftMs:     +r.baseTtftMs,
  rackSize:       r.rackSize,
  priceUSD:       +r.priceUSD,
  note:           r.note,
}]))

const GPU_GROUPS = (() => {
  const map = new Map()
  _gpuRows.forEach(r => {
    if (!map.has(r.group)) map.set(r.group, [])
    map.get(r.group).push(r.id)
  })
  return [...map.entries()].map(([label, ids]) => ({ label, ids }))
})()

const DEFAULTS   = { gpuId: 'h200-hgx', cardCount: 4, workloadId: 'voice-agent' }
const REF_TFLOPS = 1979 // H200 SXM baseline for image gen scaling

// ─── Simulation engine ────────────────────────────────────────────────────────
function computeMetrics(gpu, numCards, workload) {
  const totalMemory    = gpu.memoryGb * numCards
  const totalBandwidth = gpu.bandwidthTBs * numCards
  const totalPower     = (gpu.tdpW * numCards) / 1000

  // ── Image generation (compute-bound, not bandwidth-bound) ──
  if (workload.isImageWorkload) {
    const imgsPerMinPerCard = (gpu.fp16Tflops / REF_TFLOPS) * workload.baseImgsPerMinPerCard
    const totalImgsPerMin   = Math.round(imgsPerMinPerCard * numCards)
    const imageLatencyMs    = Math.round(60000 / imgsPerMinPerCard)
    const memForJobs        = Math.max(0, totalMemory - workload.modelSizeGb)
    const concurrentUsers   = Math.floor(memForJobs / workload.kvPerSessionGb)
    return {
      totalMemoryGb: totalMemory, totalBandwidthTBs: totalBandwidth, totalPowerKw: totalPower,
      concurrentUsers, ttftMs: 0, generationMs: imageLatencyMs, e2eMs: imageLatencyMs,
      totalTps: totalImgsPerMin, modelTooLarge: false,
    }
  }

  // ── LLM workloads ──
  const scale = workload.modelSizeGb / 14  // 14 GB = 7B BF16 baseline

  // NVLink: tensor-parallel, memory pools
  if (gpu.interconnect === 'nvlink') {
    const availableKV   = Math.max(0, totalMemory - workload.modelSizeGb)
    const concurrentUsers = workload.kvPerSessionGb > 0
      ? Math.floor(availableKV / workload.kvPerSessionGb) : 999
    const adjTps        = (gpu.baseTpsPerCard / scale) * numCards
    const ttftMs        = Math.round((gpu.baseTtftMs * scale) / numCards * 1.15)
    const generationMs  = workload.avgResponseTokens > 0
      ? Math.round((workload.avgResponseTokens / adjTps) * 1000) : 0
    const e2eMs = workload.pipelinePreMs + ttftMs + generationMs + workload.pipelinePostMs
    return {
      totalMemoryGb: totalMemory, totalBandwidthTBs: totalBandwidth, totalPowerKw: totalPower,
      concurrentUsers, ttftMs, generationMs, e2eMs, totalTps: Math.round(adjTps), modelTooLarge: false,
    }
  }

  // PCIe: multi-instance, each card holds its own full model copy
  if (workload.modelSizeGb > gpu.memoryGb) {
    return {
      totalMemoryGb: totalMemory, totalBandwidthTBs: totalBandwidth, totalPowerKw: totalPower,
      concurrentUsers: 0, ttftMs: 0, generationMs: 0, e2eMs: 0, totalTps: 0, modelTooLarge: true,
    }
  }
  const perCardKV       = Math.max(0, gpu.memoryGb - workload.modelSizeGb)
  const perCardUsers    = workload.kvPerSessionGb > 0 ? Math.floor(perCardKV / workload.kvPerSessionGb) : 999
  const concurrentUsers = perCardUsers * numCards
  const adjTps          = gpu.baseTpsPerCard / scale
  const ttftMs          = Math.round(gpu.baseTtftMs * scale)
  const generationMs    = workload.avgResponseTokens > 0
    ? Math.round((workload.avgResponseTokens / adjTps) * 1000) : 0
  const e2eMs = workload.pipelinePreMs + ttftMs + generationMs + workload.pipelinePostMs
  return {
    totalMemoryGb: totalMemory, totalBandwidthTBs: totalBandwidth, totalPowerKw: totalPower,
    concurrentUsers, ttftMs, generationMs, e2eMs, totalTps: Math.round(adjTps), modelTooLarge: false,
  }
}

const Q = { good: 'text-emerald-600', warn: 'text-amber-500', bad: 'text-red-500', neutral: 'text-[#0071e3]' }
const QS = { good: 'text-emerald-500', warn: 'text-amber-400', bad: 'text-red-400', neutral: 'text-gray-400' }

// ─── Sub-components ───────────────────────────────────────────────────────────

function MetricCard({ label, value, unit, sub, quality, tooltip }) {
  const color = Q[quality || 'neutral']
  return (
    <motion.div layout title={tooltip} className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5 flex flex-col gap-1.5 cursor-default min-w-0 overflow-hidden">
      <span className="text-xs font-medium text-gray-400 uppercase tracking-wider font-[Montserrat,sans-serif] leading-tight break-words">{label}</span>
      <AnimatePresence mode="wait">
        <motion.div key={value}
          initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -6 }}
          transition={{ duration: 0.2 }}
          className={`text-3xl font-bold leading-tight break-all ${color}`}
          style={{ fontFamily: 'Playfair Display, serif' }}
        >
          {value}<span className="text-base font-medium ml-1 text-gray-500">{unit}</span>
        </motion.div>
      </AnimatePresence>
      {sub && <span className={`text-xs leading-snug ${quality && quality !== 'neutral' ? QS[quality] : 'text-gray-400'}`}>{sub}</span>}
      {tooltip && <span className="text-[10px] text-gray-300 leading-tight mt-0.5 hidden sm:block">{tooltip}</span>}
    </motion.div>
  )
}

function LatencyBar({ metrics, workload, label, accentClass }) {
  const { ttftMs, generationMs } = metrics
  const pre  = workload.pipelinePreMs
  const post = workload.pipelinePostMs

  const segments = [
    workload.pipelinePreLabel  && { label: workload.pipelinePreLabel,  value: pre,          color: 'bg-sky-400',    textColor: 'text-sky-500'    },
    ttftMs > 0                 && { label: 'TTFT',                     value: ttftMs,        color: 'bg-indigo-500', textColor: 'text-indigo-500'  },
    generationMs > 0           && { label: workload.isImageWorkload ? 'Diffusion' : 'Generation', value: generationMs, color: 'bg-violet-500', textColor: 'text-violet-500' },
    workload.pipelinePostLabel && { label: workload.pipelinePostLabel, value: post,          color: 'bg-purple-400', textColor: 'text-purple-400'  },
  ].filter(Boolean)

  const total = segments.reduce((s, x) => s + x.value, 0)
  if (total === 0) return null
  const pct = (v) => `${((v / total) * 100).toFixed(1)}%`

  return (
    <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5">
      <h3 className="text-sm font-medium text-gray-400 uppercase tracking-widest mb-1 font-[Montserrat,sans-serif]">Latency Breakdown</h3>
      {label
        ? <p className={`text-sm font-semibold mb-3 ${accentClass}`}>{label} — {total} ms total</p>
        : <p className="text-sm text-gray-400 mb-3">{total} ms total</p>
      }
      <div className="flex rounded-full overflow-hidden h-8 w-full">
        {segments.map((s) => (
          <motion.div key={s.label} layout
            className={`${s.color} flex items-center justify-center overflow-hidden`}
            style={{ width: pct(s.value) }}
            transition={{ duration: 0.4, ease: 'easeInOut' }}
          >
            <span className="text-white text-sm font-semibold whitespace-nowrap px-1 hidden sm:block">{s.value}ms</span>
          </motion.div>
        ))}
      </div>
      <div className="flex sm:hidden gap-2 mt-2">
        {segments.map((s) => (
          <div key={s.label} className="flex-1 text-center">
            <div className={`text-xs font-bold ${s.textColor}`}>{s.value}ms</div>
            <div className="text-[10px] text-gray-400 truncate">{s.label}</div>
          </div>
        ))}
      </div>
      <div className="flex flex-wrap gap-x-4 gap-y-1 mt-3">
        {segments.map((s) => (
          <div key={s.label} className="flex items-center gap-1.5">
            <span className={`w-2.5 h-2.5 rounded-sm ${s.color}`} />
            <span className="text-sm text-gray-500">{s.label} <span className="font-medium text-gray-700">{s.value}ms</span></span>
          </div>
        ))}
      </div>
    </div>
  )
}

function ScalingChart({ gpu, workload, accentClass }) {
  const maxVal = useMemo(() => {
    const vals = gpu.validCounts.map(n => computeMetrics(gpu, n, workload).concurrentUsers)
    return Math.max(...vals, 1)
  }, [gpu, workload])

  return (
    <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5">
      <h3 className="text-sm font-medium text-gray-400 uppercase tracking-widest mb-4 font-[Montserrat,sans-serif]">
        Concurrent {gpu.validCounts.length > 1 ? workload.sessionNoun.charAt(0).toUpperCase() + workload.sessionNoun.slice(1) : 'Capacity'} vs Card Count
      </h3>
      <div className="flex items-end gap-2 h-32">
        {gpu.validCounts.map((n) => {
          const m = computeMetrics(gpu, n, workload)
          const h = (m.concurrentUsers / maxVal) * 100
          return (
            <div key={n} className="flex flex-col items-center gap-1 flex-1 min-w-0">
              <span className="text-sm font-semibold text-gray-700 truncate">{m.modelTooLarge ? '—' : m.concurrentUsers}</span>
              <motion.div layout className={`w-full rounded-t-lg opacity-80 ${accentClass || 'bg-[#0071e3]'}`}
                style={{ height: `${m.modelTooLarge ? 0 : h}%` }} transition={{ duration: 0.4 }} />
              <span className="text-sm text-gray-400">{n}×</span>
            </div>
          )
        })}
      </div>
    </div>
  )
}

function MemoryPanel({ gpu, cardCount, metrics, workload }) {
  const kvUsed  = Math.min(metrics.concurrentUsers * workload.kvPerSessionGb, Math.max(0, metrics.totalMemoryGb - workload.modelSizeGb))
  const modPct  = (workload.modelSizeGb / metrics.totalMemoryGb) * 100
  const kvPct   = (kvUsed / metrics.totalMemoryGb) * 100
  const freePct = Math.max(0, 100 - modPct - kvPct)
  const freeGb  = Math.max(0, metrics.totalMemoryGb - workload.modelSizeGb - kvUsed)
  return (
    <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5">
      <h3 className="text-sm font-medium text-gray-400 uppercase tracking-widest mb-4 font-[Montserrat,sans-serif]">
        Memory Allocation — {metrics.totalMemoryGb} GB total
      </h3>
      <div className="flex rounded-full overflow-hidden h-6 w-full">
        <motion.div layout className="bg-indigo-500 h-full" style={{ width: `${modPct}%` }}  transition={{ duration: 0.4 }} />
        <motion.div layout className="bg-violet-400 h-full" style={{ width: `${kvPct}%` }}   transition={{ duration: 0.4 }} />
        <motion.div layout className="bg-gray-100 h-full"   style={{ width: `${freePct}%` }} transition={{ duration: 0.4 }} />
      </div>
      <div className="flex flex-wrap gap-x-4 gap-y-1 mt-3 text-sm text-gray-500">
        <span className="flex items-center gap-1.5"><span className="w-2.5 h-2.5 rounded-sm bg-indigo-500" />Model <b className="text-gray-700">{workload.modelSizeGb} GB</b></span>
        <span className="flex items-center gap-1.5"><span className="w-2.5 h-2.5 rounded-sm bg-violet-400" />{workload.isImageWorkload ? 'Activations' : 'KV cache'} <b className="text-gray-700">{kvUsed.toFixed(0)} GB</b></span>
        <span className="flex items-center gap-1.5"><span className="w-2.5 h-2.5 rounded-sm bg-gray-200" />Free <b className="text-gray-700">{freeGb.toFixed(0)} GB</b></span>
      </div>
      <div className="mt-4 pt-4 border-t border-gray-100 space-y-1.5">
        {[
          ['Model',             workload.modelLabel],
          [<Term id="memory_bw">Memory bandwidth</Term>,  `${(gpu.bandwidthTBs * 1000 * cardCount).toFixed(0)} GB/s total`],
          [<Term id={gpu.interconnect === 'nvlink' ? 'nvlink' : 'pcie'}>Interconnect</Term>,      gpu.interconnect === 'nvlink' ? `NVLink (${gpu.nvlinkBw}/card)` : 'PCIe Gen5'],
          !workload.isImageWorkload && [<Term id="kv_cache">KV cache/session</Term>, `${workload.kvPerSessionGb * 1024} MB`],
          [<Term id="architecture">Architecture</Term>,      gpu.architecture],
        ].filter(Boolean).map(([k, v], i) => (
          <div key={i} className="flex justify-between text-sm">
            <span className="text-gray-400 font-[Montserrat,sans-serif]">{k}</span>
            <span className="font-semibold text-gray-700">{v}</span>
          </div>
        ))}
      </div>
    </div>
  )
}

// ─── Config Panel ─────────────────────────────────────────────────────────────

function ConfigPanel({ slot, gpuId, cardCount, onGpuChange, onCardChange, accentBg, accentText, accentBorder }) {
  const gpu = GPU_CATALOG[gpuId]
  return (
    <div className={`bg-white rounded-2xl border-2 ${accentBorder} shadow-sm p-6 flex flex-col gap-5`}>
      <div className={`flex items-center gap-2 text-sm font-bold uppercase tracking-widest ${accentText} font-[Montserrat,sans-serif]`}>
        <span className={`w-5 h-5 rounded-full ${accentBg} text-white flex items-center justify-center text-[10px] font-bold`}>{slot}</span>
        Config {slot}
      </div>
      <div className="space-y-1.5">
        <label className="block text-sm font-semibold text-gray-700 font-[Montserrat,sans-serif]">GPU Model</label>
        <select value={gpuId} onChange={(e) => onGpuChange(e.target.value)}
          className="w-full rounded-xl border border-gray-200 bg-gray-50 px-4 py-3 text-sm text-gray-900 font-[Montserrat,sans-serif] focus:outline-none focus:ring-2 focus:ring-[#0071e3] focus:border-transparent appearance-none cursor-pointer"
        >
          {GPU_GROUPS.map((g) => (
            <optgroup key={g.label} label={g.label}>
              {g.ids.map((id) => <option key={id} value={id}>{GPU_CATALOG[id].name}</option>)}
            </optgroup>
          ))}
        </select>
        <p className="text-sm text-gray-400 leading-snug">{gpu.note}</p>
      </div>
      <div className="space-y-2">
        <div className="flex items-center justify-between">
          <label className="block text-sm font-semibold text-gray-700 font-[Montserrat,sans-serif]">Cards</label>
          <span className={`text-2xl font-bold ${accentText}`} style={{ fontFamily: 'Playfair Display, serif' }}>{cardCount}×</span>
        </div>
        <input type="range" min={0} max={gpu.validCounts.length - 1} step={1}
          value={gpu.validCounts.indexOf(cardCount)}
          onChange={(e) => onCardChange(gpu.validCounts[parseInt(e.target.value)])}
          className="w-full accent-[#0071e3] cursor-pointer"
        />
        <div className="flex justify-between">
          {gpu.validCounts.map((n) => (
            <button key={n} onClick={() => onCardChange(n)}
              className={`text-sm px-2 py-1 rounded-lg font-[Montserrat,sans-serif] transition-colors ${cardCount === n ? `${accentBg} text-white font-semibold` : 'text-gray-400 hover:text-gray-700'}`}
            >{n}×</button>
          ))}
        </div>
      </div>
      <div className="pt-4 border-t border-gray-100 flex flex-wrap gap-x-5 gap-y-1.5 text-sm text-gray-500 font-[Montserrat,sans-serif]">
        <span><b className="text-gray-700">{gpu.memoryGb} GB</b> {gpu.memoryType}/card</span>
        <span><b className="text-gray-700">{(gpu.bandwidthTBs * 1000).toFixed(0)} GB/s</b> <Term id="memory_bw">BW/card</Term></span>
        <span><b className="text-gray-700">{gpu.tdpW} W</b> <Term id="tdp">TDP</Term></span>
        <span><b className="text-gray-700">{gpu.fp16Tflops.toLocaleString()}</b> <Term id="tflops">TFLOPS</Term> <Term id="fp16">FP16</Term></span>
        {gpu.nvlinkBw && <span><b className="text-gray-700">{gpu.nvlinkBw}</b> <Term id="nvlink">NVLink</Term></span>}
      </div>
    </div>
  )
}

// ─── Compare Table ────────────────────────────────────────────────────────────

function CompareTable({ gpuA, countA, mA, gpuB, countB, mB, workload }) {
  const rows = [
    { label: `Concurrent ${workload.sessionNoun}`, unit: workload.sessionNoun, a: mA.concurrentUsers, b: mB.concurrentUsers, higherBetter: true, fmt: (v) => v.toLocaleString(), note: '' },
    ...(!workload.isImageWorkload && workload.showTtft ? [
      { label: <Term id="ttft">TTFT</Term>, unit: 'ms', a: mA.ttftMs, b: mB.ttftMs, higherBetter: false, fmt: (v) => v, note: 'time to first token' },
    ] : []),
    { label: workload.latencyLabel, unit: 'ms', a: mA.e2eMs, b: mB.e2eMs, higherBetter: false, fmt: (v) => v, note: '' },
    { label: workload.throughputLabel === 'imgs/min' ? 'Throughput' : 'Throughput', unit: workload.throughputLabel, a: mA.totalTps, b: mB.totalTps, higherBetter: true, fmt: (v) => v.toLocaleString(), note: workload.isImageWorkload ? '' : (gpuA.interconnect === 'nvlink' ? 'agg.' : 'per inst.') },
    { label: <Term id="gpu_memory">GPU Memory</Term>,  unit: 'GB',  a: mA.totalMemoryGb, b: mB.totalMemoryGb, higherBetter: true,  fmt: (v) => v,          note: '' },
    { label: <Term id="power_draw">Power Draw</Term>,  unit: 'kW',  a: mA.totalPowerKw,  b: mB.totalPowerKw,  higherBetter: false, fmt: (v) => v.toFixed(1), note: 'lower = cheaper' },
  ]

  return (
    <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
      <div className="px-6 py-4 border-b border-gray-100">
        <h3 className="text-sm font-medium text-gray-400 uppercase tracking-widest font-[Montserrat,sans-serif]">Side-by-Side Comparison</h3>
      </div>
      <div className="grid grid-cols-[1fr_2fr_auto_2fr] gap-0 px-6 py-3 bg-gray-50 border-b border-gray-100 text-sm font-semibold font-[Montserrat,sans-serif]">
        <span className="text-sky-600 truncate">A — {countA}× {gpuA.shortName}</span>
        <span />
        <span className="text-center text-gray-400 uppercase tracking-widest px-3">Metric</span>
        <span className="text-right text-emerald-600 truncate">B — {countB}× {gpuB.shortName}</span>
      </div>
      {rows.map((row, i) => {
        const aWins    = row.higherBetter ? row.a >= row.b : row.a <= row.b
        const tied     = row.a === row.b
        const deltaPct = row.b !== 0 ? Math.round(Math.abs((row.a - row.b) / row.b) * 100) : 0
        return (
          <div key={i} className="grid grid-cols-[1fr_auto_auto_auto_1fr] items-center gap-2 px-6 py-4 border-b border-gray-50 last:border-0">
            <div className="text-right">
              <span className="text-xl font-bold text-gray-800" style={{ fontFamily: 'Playfair Display, serif' }}>{mA.modelTooLarge ? '—' : row.fmt(row.a)}</span>
              <span className="text-sm text-gray-400 ml-1">{row.unit}</span>
              {row.note && <div className="text-xs text-gray-400">{row.note}</div>}
            </div>
            <div className="flex justify-center w-12">
              {!tied && !mA.modelTooLarge && !mB.modelTooLarge && aWins && (
                <span className="text-sm font-bold bg-sky-100 text-sky-600 px-2 py-0.5 rounded-full font-[Montserrat,sans-serif] whitespace-nowrap">
                  {deltaPct > 0 ? `+${deltaPct}%` : '✓'}
                </span>
              )}
            </div>
            <div className="text-center px-2">
              <div className="text-sm font-semibold text-gray-600 font-[Montserrat,sans-serif] whitespace-nowrap">{row.label}</div>
              <div className="text-xs text-gray-400">{row.higherBetter ? '↑ more is better' : '↓ less is better'}</div>
            </div>
            <div className="flex justify-center w-12">
              {!tied && !mA.modelTooLarge && !mB.modelTooLarge && !aWins && (
                <span className="text-sm font-bold bg-emerald-100 text-emerald-600 px-2 py-0.5 rounded-full font-[Montserrat,sans-serif] whitespace-nowrap">
                  {deltaPct > 0 ? `+${deltaPct}%` : '✓'}
                </span>
              )}
            </div>
            <div className="text-left">
              <span className="text-xl font-bold text-gray-800" style={{ fontFamily: 'Playfair Display, serif' }}>{mB.modelTooLarge ? '—' : row.fmt(row.b)}</span>
              <span className="text-sm text-gray-400 ml-1">{row.unit}</span>
            </div>
          </div>
        )
      })}
    </div>
  )
}

// ─── Workload Tabs ────────────────────────────────────────────────────────────

function WorkloadTabs({ selected, onChange }) {
  return (
    <div className="flex gap-2 overflow-x-auto pb-1 scrollbar-none">
      {Object.values(WORKLOAD_CATALOG).map((w) => (
        <button key={w.id} onClick={() => onChange(w.id)}
          className={`flex items-center gap-2 px-4 py-2 rounded-full text-sm font-medium whitespace-nowrap font-[Montserrat,sans-serif] transition-all border ${
            selected === w.id
              ? 'bg-gray-900 text-white border-gray-900'
              : 'bg-white text-gray-500 border-gray-200 hover:border-gray-400 hover:text-gray-700'
          }`}
        >
          {w.name}
        </button>
      ))}
    </div>
  )
}

const ACCENTS = [
  { bg: 'bg-sky-500',     text: 'text-sky-600',     border: 'border-sky-200',     light: 'bg-sky-50',     badge: 'bg-sky-100 text-sky-700'     },
  { bg: 'bg-emerald-500', text: 'text-emerald-600', border: 'border-emerald-200', light: 'bg-emerald-50', badge: 'bg-emerald-100 text-emerald-700' },
  { bg: 'bg-amber-500',   text: 'text-amber-600',   border: 'border-amber-200',   light: 'bg-amber-50',   badge: 'bg-amber-100 text-amber-700'   },
  { bg: 'bg-rose-500',    text: 'text-rose-600',     border: 'border-rose-200',   light: 'bg-rose-50',    badge: 'bg-rose-100 text-rose-700'     },
]
const SLOTS = ['A', 'B', 'C', 'D']

function MultiCompareTable({ configs, gpus, metricsArr, workload }) {
  const costsArr = configs.map((c, i) => computeCosts(gpus[i], c.count, metricsArr[i].concurrentUsers))

  const rows = [
    { label: <Term id="concurrent">Concurrent Users</Term>, unit: '', vals: metricsArr.map(m => m.concurrentUsers), fmt: v => v.toLocaleString(), higherBetter: true },
    { label: <Term id="ttft">TTFT</Term>,           unit: 'ms', vals: metricsArr.map(m => m.ttftMs),          fmt: v => v,               higherBetter: false },
    { label: 'E2E Latency',                          unit: 'ms', vals: metricsArr.map(m => m.e2eMs),           fmt: v => v,               higherBetter: false },
    { label: <Term id="throughput">Throughput</Term>, unit: workload.throughputLabel, vals: metricsArr.map(m => m.totalTps), fmt: v => v.toLocaleString(), higherBetter: true },
    { label: <Term id="gpu_memory">GPU Memory</Term>, unit: 'GB', vals: metricsArr.map(m => m.totalMemoryGb),  fmt: v => v,               higherBetter: true },
    { label: <Term id="power_draw">Power Draw</Term>, unit: 'kW', vals: metricsArr.map(m => m.totalPowerKw),   fmt: v => v.toFixed(1),    higherBetter: false },
    { label: <Term id="cluster_cost">Cluster Cost</Term>, unit: '', vals: costsArr.map(c => c.clusterCost),    fmt: fmt$,                 higherBetter: false },
    { label: <Term id="annual_power">Annual Power</Term>, unit: '/yr', vals: costsArr.map(c => c.annualPowerUSD), fmt: fmt$,              higherBetter: false },
    { label: <Term id="cost_per_user">Cost / User</Term>, unit: '', vals: costsArr.map(c => c.costPerUser),    fmt: fmt$,                 higherBetter: false },
  ]

  return (
    <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-x-auto">
      <table className="w-full text-sm font-[Montserrat,sans-serif] min-w-[560px]">
        <thead>
          <tr className="border-b border-gray-100 bg-gray-50">
            <th className="text-left px-5 py-3 text-xs font-bold uppercase tracking-widest text-gray-400 w-40">Metric</th>
            {configs.map((c, i) => {
              const acc = ACCENTS[i]
              return (
                <th key={i} className="px-4 py-3 text-center">
                  <div className={`text-xs font-bold uppercase tracking-widest ${acc.text}`}>{SLOTS[i]}</div>
                  <div className="text-xs text-gray-600 font-semibold">{gpus[i].shortName}</div>
                  <div className="text-xs text-gray-400">{c.count}× cards</div>
                </th>
              )
            })}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, ri) => {
            const validVals = row.vals.filter((v, i) => !metricsArr[i].modelTooLarge)
            const best = validVals.length ? (row.higherBetter ? Math.max(...validVals) : Math.min(...validVals)) : null
            return (
              <tr key={ri} className="border-b border-gray-50 last:border-0 hover:bg-gray-50/50 transition-colors">
                <td className="px-5 py-3 text-xs font-semibold text-gray-500">{row.label}{row.unit && <span className="text-gray-400 ml-1 font-normal">{row.unit}</span>}</td>
                {row.vals.map((v, i) => {
                  const isBest = best !== null && v === best && !metricsArr[i].modelTooLarge
                  const acc = ACCENTS[i]
                  return (
                    <td key={i} className={`px-4 py-3 text-center ${isBest ? acc.light : ''}`}>
                      {metricsArr[i].modelTooLarge ? (
                        <span className="text-gray-300">—</span>
                      ) : (
                        <div>
                          <span className={`text-base font-bold ${isBest ? acc.text : 'text-gray-700'}`} style={{ fontFamily: 'Playfair Display, serif' }}>
                            {row.fmt(v)}
                          </span>
                          {isBest && <div className={`text-[10px] font-bold uppercase tracking-widest ${acc.text} mt-0.5`}>best</div>}
                        </div>
                      )}
                    </td>
                  )
                })}
              </tr>
            )
          })}
        </tbody>
      </table>
    </div>
  )
}

// ─── Main page ────────────────────────────────────────────────────────────────

export default function ThroughputSim() {
  const [numConfigs, setNumConfigs] = useState(1)
  const [configs, setConfigs] = useState([
    { gpuId: 'h200-hgx', count: 4 },
    { gpuId: 'h100-sxm', count: 4 },
    { gpuId: 'rtx-pro-6000-blackwell', count: 4 },
    { gpuId: 'rtx-6000-ada', count: 4 },
  ])
  const [workloadId, setWorkloadId]     = useState(DEFAULTS.workloadId)
  const [activeTerm, setActiveTerm]     = useState(null)

  const workload = WORKLOAD_CATALOG[workloadId]

  const updateConfig = (i, patch) =>
    setConfigs(prev => prev.map((c, idx) => idx === i ? { ...c, ...patch } : c))

  const handleGpuChange = (i, id) => {
    const g = GPU_CATALOG[id]
    const count = configs[i].count
    const nearest = g.validCounts.includes(count) ? count : g.validCounts.reduce((a, b) => Math.abs(b - count) < Math.abs(a - count) ? b : a)
    updateConfig(i, { gpuId: id, count: nearest })
  }

  const handleReset = () => {
    setNumConfigs(1)
    setConfigs([
      { gpuId: 'h200-hgx', count: 4 },
      { gpuId: 'h100-sxm', count: 4 },
      { gpuId: 'rtx-pro-6000-blackwell', count: 4 },
      { gpuId: 'rtx-6000-ada', count: 4 },
    ])
    setWorkloadId(DEFAULTS.workloadId)
  }

  const allGpus    = configs.map(c => GPU_CATALOG[c.gpuId])
  const allMetrics = configs.map((c, i) => computeMetrics(allGpus[i], c.count, workload))

  // Backward-compat aliases for single-mode
  const gpu     = allGpus[0]
  const count   = configs[0].count
  const metrics = allMetrics[0]


  return (
    <TermCtx.Provider value={{ setTerm: setActiveTerm }}>
      <ExplanationPanel termId={activeTerm} />
    <div className="min-h-screen bg-gradient-to-b from-slate-50 via-white to-slate-50 text-gray-900 selection:bg-black selection:text-white">

      {/* Page header — sticky */}
      <div className="sticky top-0 z-40 bg-white/90 backdrop-blur-md border-b border-gray-100">
      <div className="max-w-6xl mx-auto pl-16 pr-6 sm:px-6 pt-8 pb-5 sm:text-center relative">
        <span className="absolute top-3 right-3 sm:top-4 sm:right-4 text-[10px] font-bold uppercase tracking-widest
                         bg-amber-100 text-amber-700 border border-amber-200 rounded-full px-3 py-1
                         font-[Montserrat,sans-serif] select-none">
          Work in progress
        </span>
        <h1 className="text-4xl sm:text-5xl font-bold text-gray-900 mb-4" style={{ fontFamily: 'Playfair Display, serif' }}>
          GPU Cluster Throughput Simulator
        </h1>
        <p className="text-gray-500 text-sm max-w-2xl mx-auto leading-relaxed font-[Montserrat,sans-serif]">
          Model the real-world capacity of NVIDIA GPU clusters for AI inference workloads.
          Pick a GPU, set your card count, and instantly see concurrent user capacity, latency breakdown,
          and power draw — across voice agents, chat APIs, and more.
        </p>
        <p className="text-gray-400 text-xs max-w-2xl mx-auto mt-2 font-[Montserrat,sans-serif] italic">
          Hover over the terms you don't understand to read an explanation.
        </p>
      </div>
      </div>

      <div className="max-w-7xl mx-auto px-6 py-8">

        {/* Two-column layout: left config sidebar + right results */}
        <div className="flex flex-col lg:flex-row gap-8 items-start">

          {/* ── Left sidebar: configuration ── */}
          <div className="w-full lg:w-72 flex-shrink-0 flex flex-col gap-5 lg:sticky lg:top-[200px]">

            {/* Workload tabs */}
            <div>
              <p className="text-xs font-bold uppercase tracking-widest text-gray-400 mb-2 font-[Montserrat,sans-serif]">Workload</p>
              <div className="flex flex-col gap-2">
                {Object.values(WORKLOAD_CATALOG).map((w) => (
                  <button key={w.id} onClick={() => setWorkloadId(w.id)}
                    className={`text-left px-4 py-2.5 rounded-full text-sm font-medium font-[Montserrat,sans-serif] transition-all border ${
                      workloadId === w.id
                        ? 'bg-gray-900 text-white border-gray-900'
                        : 'bg-white text-gray-500 border-gray-200 hover:border-gray-400 hover:text-gray-700'
                    }`}
                  >{w.name}</button>
                ))}
              </div>
            </div>

            {/* Config count selector */}
            <div>
              <p className="text-xs font-bold uppercase tracking-widest text-gray-400 mb-2 font-[Montserrat,sans-serif]">Configurations</p>
              <div className="flex gap-1.5">
                {[1, 2, 3, 4].map(n => (
                  <button key={n} onClick={() => setNumConfigs(n)}
                    className={`flex-1 py-2 rounded-full text-sm font-bold font-[Montserrat,sans-serif] border transition-all ${
                      numConfigs === n ? 'bg-black text-white border-black' : 'bg-white text-gray-500 border-gray-200 hover:border-gray-400'
                    }`}
                  >{n}</button>
                ))}
              </div>
            </div>

            {/* Config panels — compact for 3-4 */}
            <AnimatePresence mode="wait">
              <motion.div key={numConfigs} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
                className="flex flex-col gap-3"
              >
                {configs.slice(0, numConfigs).map((cfg, i) => {
                  const acc = ACCENTS[i]
                  const g = GPU_CATALOG[cfg.gpuId]
                  return numConfigs <= 2 ? (
                    <ConfigPanel key={i} slot={SLOTS[i]} gpuId={cfg.gpuId} cardCount={cfg.count}
                      onGpuChange={(id) => handleGpuChange(i, id)}
                      onCardChange={(n) => updateConfig(i, { count: n })}
                      accentBg={acc.bg} accentText={acc.text} accentBorder={acc.border} />
                  ) : (
                    // Compact card for 3-4 configs
                    <div key={i} className={`bg-white rounded-xl border-2 ${acc.border} p-3 flex flex-col gap-2`}>
                      <div className={`flex items-center gap-2 text-xs font-bold uppercase tracking-widest ${acc.text} font-[Montserrat,sans-serif]`}>
                        <span className={`w-4 h-4 rounded-full ${acc.bg} text-white flex items-center justify-center text-[9px] font-bold`}>{SLOTS[i]}</span>
                        Config {SLOTS[i]}
                      </div>
                      <select value={cfg.gpuId} onChange={e => handleGpuChange(i, e.target.value)}
                        className="w-full rounded-lg border border-gray-200 bg-gray-50 px-2 py-1.5 text-xs text-gray-900 font-[Montserrat,sans-serif] focus:outline-none appearance-none cursor-pointer"
                      >
                        {GPU_GROUPS.map(grp => (
                          <optgroup key={grp.label} label={grp.label}>
                            {grp.ids.map(id => <option key={id} value={id}>{GPU_CATALOG[id].shortName}</option>)}
                          </optgroup>
                        ))}
                      </select>
                      <div className="flex items-center gap-2">
                        <span className="text-xs text-gray-500 font-[Montserrat,sans-serif]">Cards</span>
                        <input type="range" min={0} max={g.validCounts.length - 1} step={1}
                          value={g.validCounts.indexOf(cfg.count)}
                          onChange={e => updateConfig(i, { count: g.validCounts[parseInt(e.target.value)] })}
                          className="flex-1 accent-[#0071e3] cursor-pointer"
                        />
                        <span className={`text-sm font-bold ${acc.text} w-8 text-right`} style={{ fontFamily: 'Playfair Display, serif' }}>{cfg.count}×</span>
                      </div>
                    </div>
                  )
                })}
              </motion.div>
            </AnimatePresence>

            {/* Reset */}
            <button onClick={handleReset} className="text-xs font-medium text-gray-500 hover:text-red-500 border border-gray-200 hover:border-red-300 rounded-full px-4 py-1.5 transition-all self-start font-[Montserrat,sans-serif]">↺  Reset to defaults</button>
          </div>

          {/* ── Right: results ── */}
          <div className="flex-1 min-w-0 space-y-6">

            {/* Workload tagline */}
            <AnimatePresence mode="wait">
              <motion.div key={workloadId}
                initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}
                transition={{ duration: 0.3 }}
              >
                <h2 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-1" style={{ fontFamily: 'Playfair Display, serif' }}>
                  {workload.tagline}
                </h2>
                <p className="text-sm text-gray-400 font-[Montserrat,sans-serif]">{workload.description}</p>
              </motion.div>
            </AnimatePresence>

        {/* Model-too-large warning — single mode only */}
        {metrics.modelTooLarge && numConfigs === 1 && (
          <div className="bg-red-50 border border-red-200 rounded-xl px-5 py-4 text-sm text-red-700 font-[Montserrat,sans-serif]">
            ⚠ The <b>{workload.modelLabel}</b> model ({workload.modelSizeGb} GB) is too large to fit in a single {gpu.shortName} card ({gpu.memoryGb} GB).
            PCIe multi-instance requires one full model copy per card. Switch to an NVLink config or a card with more memory.
          </div>
        )}

        {/* Single mode results */}
        <AnimatePresence>
          {numConfigs === 1 && !metrics.modelTooLarge && (
            <motion.div key="single-results" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="space-y-6">
              <div>
                <h3 className="text-xs font-medium text-gray-400 uppercase tracking-widest mb-4 font-[Montserrat,sans-serif]">
                  Key Metrics — {count}× {gpu.shortName} · {workload.name}
                </h3>
                <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 min-w-0">
                  <MetricCard label={`Concurrent ${workload.sessionNoun}`} value={metrics.concurrentUsers.toLocaleString()} unit={workload.sessionNoun}
                    sub={`simultaneous ${workload.sessionNoun}`} quality="neutral"
                    tooltip={`How many ${workload.sessionNoun} this cluster can handle at once`} />
                  {!workload.isImageWorkload && workload.showTtft && (
                    <MetricCard label={<Term id="ttft">TTFT</Term>} value={metrics.ttftMs} unit="ms" sub="time to first token" quality="neutral"
                      tooltip="How quickly the model starts responding — critical for perceived responsiveness" />
                  )}
                  <MetricCard label={workload.latencyLabel} value={metrics.e2eMs} unit="ms"
                    sub="end-to-end"
                    quality="neutral"
                    tooltip={`End-to-end time for one ${workload.sessionNoun.replace(/s$/, '')}`} />
                  <MetricCard label={<Term id="throughput">Throughput</Term>} value={metrics.totalTps.toLocaleString()} unit={workload.throughputLabel}
                    sub={workload.isImageWorkload ? 'total cluster' : gpu.interconnect === 'nvlink' ? 'aggregate' : 'per instance'}
                    quality="neutral" tooltip={`${workload.isImageWorkload ? 'Images per minute' : 'Tokens per second'} generated by the cluster`} />
                  <MetricCard label={<Term id="gpu_memory">GPU Memory</Term>} value={metrics.totalMemoryGb} unit="GB" sub={`${gpu.memoryType} total`} quality="neutral"
                    tooltip="Total video memory — limits how many sessions run in parallel" />
                  <MetricCard label={<Term id="power_draw">Power Draw</Term>} value={metrics.totalPowerKw.toFixed(1)} unit="kW"
                    sub={`${(metrics.totalPowerKw * 3412).toFixed(0)} BTU/hr`} quality="neutral"
                    tooltip="Total electricity draw at full load" />
                </div>
              </div>
              <LatencyBar metrics={metrics} workload={workload} />
              <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
                <CostPanel gpu={gpu} numCards={count} concurrentUsers={metrics.concurrentUsers} />
                <ScalingChart gpu={gpu} workload={workload} />
                <MemoryPanel gpu={gpu} cardCount={count} metrics={metrics} workload={workload} />
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* 2-config compare results */}
        <AnimatePresence>
          {numConfigs === 2 && (
            <motion.div key="compare-2" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} className="space-y-8">
              {(allMetrics[0].modelTooLarge || allMetrics[1].modelTooLarge) && (
                <div className="bg-red-50 border border-red-200 rounded-xl px-5 py-4 text-sm text-red-700 font-[Montserrat,sans-serif]">
                  ⚠ {allMetrics[0].modelTooLarge ? `Config A: ${allGpus[0].shortName} (${allGpus[0].memoryGb} GB)` : ''}{allMetrics[0].modelTooLarge && allMetrics[1].modelTooLarge ? ' and ' : ''}{allMetrics[1].modelTooLarge ? `Config B: ${allGpus[1].shortName} (${allGpus[1].memoryGb} GB)` : ''}
                  {' '}cannot fit the {workload.modelLabel} model ({workload.modelSizeGb} GB) in a single PCIe card.
                </div>
              )}
              <CompareTable gpuA={allGpus[0]} countA={configs[0].count} mA={allMetrics[0]} gpuB={allGpus[1]} countB={configs[1].count} mB={allMetrics[1]} workload={workload} />
              <div className="grid sm:grid-cols-2 gap-4">
                <LatencyBar metrics={allMetrics[0]} workload={workload} label={`A — ${configs[0].count}× ${allGpus[0].shortName}`} accentClass="text-sky-600" />
                <LatencyBar metrics={allMetrics[1]} workload={workload} label={`B — ${configs[1].count}× ${allGpus[1].shortName}`} accentClass="text-emerald-600" />
              </div>
              <div className="grid sm:grid-cols-2 gap-6">
                <div className="space-y-4">
                  <p className="text-sm font-semibold text-sky-600 font-[Montserrat,sans-serif]">Config A — {configs[0].count}× {allGpus[0].shortName}</p>
                  <ScalingChart gpu={allGpus[0]} workload={workload} accentClass="bg-sky-500" />
                  <MemoryPanel gpu={allGpus[0]} cardCount={configs[0].count} metrics={allMetrics[0]} workload={workload} />
                  <CostPanel gpu={allGpus[0]} numCards={configs[0].count} concurrentUsers={allMetrics[0].concurrentUsers} />
                </div>
                <div className="space-y-4">
                  <p className="text-sm font-semibold text-emerald-600 font-[Montserrat,sans-serif]">Config B — {configs[1].count}× {allGpus[1].shortName}</p>
                  <ScalingChart gpu={allGpus[1]} workload={workload} accentClass="bg-emerald-500" />
                  <MemoryPanel gpu={allGpus[1]} cardCount={configs[1].count} metrics={allMetrics[1]} workload={workload} />
                  <CostPanel gpu={allGpus[1]} numCards={configs[1].count} concurrentUsers={allMetrics[1].concurrentUsers} />
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* 3-4 config compare results */}
        <AnimatePresence>
          {numConfigs >= 3 && (
            <motion.div key="compare-multi" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0 }} className="space-y-6">
              <MultiCompareTable
                configs={configs.slice(0, numConfigs)}
                gpus={allGpus.slice(0, numConfigs)}
                metricsArr={allMetrics.slice(0, numConfigs)}
                workload={workload}
              />
              <div className={`grid gap-4 sm:grid-cols-${numConfigs}`}>
                {configs.slice(0, numConfigs).map((cfg, i) => {
                  const acc = ACCENTS[i]
                  const g = allGpus[i]
                  const m = allMetrics[i]
                  if (m.modelTooLarge) return null
                  return (
                    <div key={i} className={`bg-white rounded-2xl border-2 ${acc.border} shadow-sm p-4 space-y-3`}>
                      <div className={`flex items-center gap-2 text-xs font-bold uppercase tracking-widest ${acc.text} font-[Montserrat,sans-serif]`}>
                        <span className={`w-4 h-4 rounded-full ${acc.bg} text-white flex items-center justify-center text-[9px] font-bold`}>{SLOTS[i]}</span>
                        {cfg.count}× {g.shortName}
                      </div>
                      <LatencyBar metrics={m} workload={workload} />
                    </div>
                  )
                })}
              </div>
            </motion.div>
          )}
        </AnimatePresence>

            {/* Assumptions */}
            <div className="bg-blue-50/60 border border-blue-100 rounded-xl p-5 font-[Montserrat,sans-serif]">
          <div className="flex items-center gap-2 mb-3">
            <svg width="16" height="16" viewBox="0 0 16 16" fill="none" aria-hidden="true" className="flex-shrink-0 text-[#0071e3]">
              <circle cx="8" cy="8" r="7" stroke="currentColor" strokeWidth="1.5" />
              <path d="M8 7v5" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
              <circle cx="8" cy="4.5" r="0.75" fill="currentColor" />
            </svg>
            <p className="text-sm font-semibold text-gray-600 uppercase tracking-widest">Model Assumptions — {workload.name}</p>
          </div>
          <ul className="space-y-1.5 text-sm text-gray-500">
            {[
              `Model: ${workload.modelLabel} (${workload.modelSizeGb} GB GPU memory). ${workload.description}.`,
              workload.isImageWorkload
                ? 'Throughput scaled from H200 baseline (~12 imgs/min for SDXL 512×512, 20 steps). Actual speed depends on resolution, steps, and scheduler.'
                : `Inference stack: vLLM + continuous batching (NVLink); TensorRT-LLM (PCIe). KV cache per session: ${workload.kvPerSessionGb * 1024} MB (~${workload.kvPerSessionGb * 2 * 1024} token context).`,
              !workload.isImageWorkload && workload.pipelinePreLabel
                ? `Pipeline: ${workload.pipelinePreLabel} (${workload.pipelinePreMs}ms) → LLM → ${workload.pipelinePostLabel} (${workload.pipelinePostMs}ms). Avg response: ${workload.avgResponseTokens} tokens.`
                : !workload.isImageWorkload
                ? `Avg response: ${workload.avgResponseTokens} tokens. No pre/post pipeline stages.`
                : null,
              'NVLink configs: tensor-parallel (model split across cards, memory pooled). PCIe: independent multi-instance (full model copy per card).',
              'Throughput figures are estimates from memory-bandwidth analysis and published benchmarks. Actual results vary with batch size, quantization, and serving stack.',
            ].filter(Boolean).map((text) => (
              <li key={text} className="flex gap-2"><span className="text-[#0071e3] flex-shrink-0">•</span><span>{text}</span></li>
            ))}
          </ul>
            </div>

          </div>{/* end right results */}
        </div>{/* end two-column flex */}
      </div>{/* end max-w wrapper */}
    </div>{/* end page */}
    </TermCtx.Provider>
  )
}
